export const USER_ACCESS = "USER_ACCESS";

export const USER_ACCESS_INVERSE = "USER_ACCESS_INVERSE";

export const USER_ACCESSNAME = "USER_ACCESSNAME";

export const USER_LOGS_DELETE = "USER_LOGS_DELETE ";
